base_global_planner: gki_3dnav_planner/GKI3dNavPlanner
controller_patience: 100.0
controller_frequency: 10.0
footprint_padding: 0.01

GKI3dNavPlanner:
  environment_type: XYT_3dCollisions
  planner_type: ARAPlanner
  allocated_time: 10.0
  initial_epsilon: 5.0
  forward_search: true
  use_freespace_heuristic: true
  freespace_costmap_out_of_map_behavior: euclidean_append
  track_expansions: true
  force_scratch_limit: 0
  #expansion_color_scheme: occupancy
  expansion_color_scheme: costmap
  trans_vel: 0.8
  rot_vel: 1.3089969389957471827

  scene_update_name: /get_planning_scene
