# move_base params:
footprint_padding: 0.01
controller_frequency: 10 # was 15
controller_patience: 100.0
base_local_planner: pose_follower_3d/PoseFollower3D
recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
  reset_distance: 3.0

aggressive_reset:
  reset_distance: 1.84
